//************************************************************************************
//**  
//**  Source name:   U:\Documents\SIN\BOYER\PROJET\Tests\Bluetooth\external\BT_MASTER_v6.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F877A
//**  
//**  Generated by:  Flowcode v6.1.3.2
//**  Date:          Monday, January 23, 2017 14:15:59
//**  Users:         50
//**  Registered to: LYC-FERRY06-V6
//**  Licence key:   HY62PA
//**  
//**  
//**     POUR UN USAGE NON COMMERCIAL
//**  
//**  http://www.matrixtsl.com
//**  
//************************************************************************************


#define MX_PIC
#define MX_CAL_PIC
#define MX_CLK_SPEED 19660800
#define FCP_NULL Unconnected_Port


#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3F72
#endif
#ifdef HI_TECH_C
__CONFIG(0x3F72);
#endif

/*========================================================================*\
   Use :Inclure les définitions de type
\*========================================================================*/
#include "C:\Program Files\Flowcode 6\CAL\internals.c"



/*========================================================================*\
   Use :panel
       :Déclarations des variables
       :Déclarations de la fonction macro
\*========================================================================*/
MX_GLOBAL MX_UINT8 FCV_IN;
MX_GLOBAL MX_UINT8 FCV_LINE;
MX_GLOBAL MX_UINT8 FCV_CHAR;
MX_GLOBAL MX_UINT8 FCV_ERR;
MX_GLOBAL MX_UINT8 FCV_RET;
MX_GLOBAL MX_UINT8 FCV_LOOP;

void FCM_NEWLINE();
void FCM_INTERRUPT_TMR0();
void FCM_INTERRUPT_PORTB();
void FCM_INTERRUPT_RB0INT();

/*========================================================================*\
   Use :v5__bluetooth0
       :Déclarations des variables
       :Déclarations de la fonction macro
\*========================================================================*/

/*========================================================================*\
   Use :v5__lcddisplay0
       :Déclarations des variables
       :Déclarations de la fonction macro
\*========================================================================*/

/*========================================================================*\
   Use :Inclure la couche d'adaptation de puce
\*========================================================================*/
#include "C:\Program Files\Flowcode 6\CAL\includes.c"


/*========================================================================*\
   Use :panel
       :Implémentations de la macro
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_NEWLINE()
{

	// Decision
	// Décision: LINE MOD 2?
	if (FCV_LINE % 2)
	{

		// Call Macro
		// Appel de la Routine Composant: v5__lcddisplay0::Cursor(0, 0)
		/* Error: Composant inconnu ou absent : v5__lcddisplay0::Cursor */;

	} else {

		// Call Macro
		// Appel de la Routine Composant: v5__lcddisplay0::Cursor(0, 1)
		/* Error: Composant inconnu ou absent : v5__lcddisplay0::Cursor */;

	}

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintNumber(LINE)
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintNumber */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII(":              ")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Decision
	// Décision: LINE MOD 2?
	if (FCV_LINE % 2)
	{

		// Call Macro
		// Appel de la Routine Composant: v5__lcddisplay0::Cursor(3, 0)
		/* Error: Composant inconnu ou absent : v5__lcddisplay0::Cursor */;

	} else {

		// Call Macro
		// Appel de la Routine Composant: v5__lcddisplay0::Cursor(3, 1)
		/* Error: Composant inconnu ou absent : v5__lcddisplay0::Cursor */;

	}

	// Calculation
	// Calcul:
	//  LINE = LINE + 1
	FCV_LINE = FCV_LINE + 1;

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_INTERRUPT_TMR0()
{

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_INTERRUPT_PORTB()
{

}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_INTERRUPT_RB0INT()
{

}



/*========================================================================*\
   Use :Principale
\*========================================================================*/
void main()
{
adcon1 = 0x07;

option_reg = 0xC0;


	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::Start()
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::Start */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII("init.")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: v5__bluetooth0::Initialize()
	/* Error: Composant inconnu ou absent : v5__bluetooth0::Initialize */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII("done.")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::StringReceive()
	/* Error: Composant inconnu ou absent : v5__bluetooth0::StringReceive */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::StringReceive()
	/* Error: Composant inconnu ou absent : v5__bluetooth0::StringReceive */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::StringReceive()
	/* Error: Composant inconnu ou absent : v5__bluetooth0::StringReceive */;

	// Delay
	// Pause: 250 ms
	FCI_DELAYBYTE_MS(250);

	// Calculation
	// Calcul:
	//  ERR = 0
	FCV_ERR = 0;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::Clear()
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::Clear */;

	//Commentaire:
	//Firmware reset
	//AT&F*

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("AT&f*")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Delay
	// Pause: 100 ms
	FCI_DELAYBYTE_MS(100);

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 100)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Autoanswer on 1 ring
	//ATS0=1

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("ATS0=1")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Allow remote !!! capture
	//ATS536=1

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("ATS536=1")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Boot up as connectable and discoverable
	//ATS512=4

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("ATS512=4")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Set the passkey
	//AT+BTK="1234"

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("AT+BTK=")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand(34)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("1234")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand(34)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Write S registers to NVM
	//AT&W

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("AT&W")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	//Commentaire:
	//Reset the device
	//ATZ

	// Calculation
	// Calcul:
	//  ERR = ERR + 1
	FCV_ERR = FCV_ERR + 1;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::CreateCommand("ATZ")
	/* Error: Composant inconnu ou absent : v5__bluetooth0::CreateCommand */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::SendCommand(1, 1)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::SendCommand */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII('.')
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: RET=v5__bluetooth0::WaitForResponse(1, 10)
	/* Error: Composant inconnu ou absent : v5__bluetooth0::WaitForResponse */;

	// Decision
	// Décision: RET <> 0?
	if (FCV_RET != 0)
	{

		// Goto Connection Point
		// Aller au Point de Jonction: [A]: A
		goto FCC_Main_A;

	// } else {

	}

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII("setup")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Delay
	// Pause: 2 s
	FCI_DELAYBYTE_S(2);

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::Clear()
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::Clear */;

	// Calculation
	// Calcul:
	//  LINE = 1
	FCV_LINE = 1;

	// Loop
	// Boucle: While 1
	while (1)
	{

		// Input
		// Entrée: PORTA -> IN
		FCV_IN = FCP_GET(F, A, 0xFF, 0);
		// Decision
		// Décision: IN = 1?
		if (FCV_IN == 1)
		{

			// Call Macro
			// Appel de la Routine Composant: v5__lcddisplay0::Clear()
			/* Error: Composant inconnu ou absent : v5__lcddisplay0::Clear */;

			// Calculation
			// Calcul:
			//  LINE = 1
			FCV_LINE = 1;

		// } else {

		}

		// Call Macro
		// Appel de la Routine Composant: RET=v5__bluetooth0::StringReceive()
		/* Error: Composant inconnu ou absent : v5__bluetooth0::StringReceive */;

		// Decision
		// Décision: RET > 0?
		if (FCV_RET > 0)
		{

			// Call Macro
			// Appel d'une Macro: NEWLINE()
			FCM_NEWLINE();

			// Calculation
			// Calcul:
			//  LOOP = 0
			FCV_LOOP = 0;

			// Loop
			// Boucle: While LOOP < RET
			while (FCV_LOOP < FCV_RET)
			{

				// Call Macro
				// Appel de la Routine Composant: CHAR=v5__bluetooth0::StringRead(LOOP)
				/* Error: Composant inconnu ou absent : v5__bluetooth0::StringRead */;

				// Call Macro
				// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII(CHAR)
				/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

				// Calculation
				// Calcul:
				//  LOOP = LOOP + 1
				FCV_LOOP = FCV_LOOP + 1;


			}

		// } else {

		}


	}

	// Connection Point
	// Point de Jonction: [A]: A
FCC_Main_A:
;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII("error")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::Cursor(0, 1)
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::Cursor */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintNumber(ERR)
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintNumber */;

	// Call Macro
	// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII(" ")
	/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	// Decision
	// Décision: RET = 255?
	if (FCV_RET == 255)
	{

		// Call Macro
		// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII("t/o")
		/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

	} else {

		// Calculation
		// Calcul:
		//  LOOP = 0
		FCV_LOOP = 0;

		// Loop
		// Boucle: While LOOP < RET
		while (FCV_LOOP < FCV_RET)
		{

			// Call Macro
			// Appel de la Routine Composant: CHAR=v5__bluetooth0::StringRead(LOOP)
			/* Error: Composant inconnu ou absent : v5__bluetooth0::StringRead */;

			// Call Macro
			// Appel de la Routine Composant: v5__lcddisplay0::PrintASCII(CHAR)
			/* Error: Composant inconnu ou absent : v5__lcddisplay0::PrintASCII */;

			// Calculation
			// Calcul:
			//  LOOP = LOOP + 1
			FCV_LOOP = FCV_LOOP + 1;


		}

	}

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interruption
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{

}




